### ISSUE TITLE
Create users database

### ISSUE THREAD

**Issue by cristinasantamarina** [cristinasantamarina/Eva#13]
- [ ] Add all current users
- [ ] Import diary entries, onboardings and surveys from emails and chatfuel api
- [ ] For each user see first conversation date, last conversation date, number of conversations, surveys filled in, word cloud, profile

**Comment by Lorenzo1985** [comment]
Hi Cris, I am here with Beni looking at the ticket. So, to summarize this one, you´d like to migrate the data in our DB. Now. We have different options. Either we use a cloud solution, which is scalable (we can get information about that), or we use an own server, which Beni could give, but we will have one day to go to the cloud anyway, or to buy a bigger server for own database. Another question is: do we still need chatfuel afterwards, or we have to program their API to FB for their functions on our own? In any of all these cases, to migrate Data we need the Chatfuel Account
